# Configurações gerais da aplicação
spring.application.name=order-management-api

# Perfil ativo (mude para 'dev' ou 'prod' conforme necessário)
# Para desenvolvimento: --spring.profiles.active=dev
# Para produção: --spring.profiles.active=prod
# Para testes: --spring.profiles.active=test
spring.profiles.active=test

# Configurações JPA comuns
spring.jpa.open-in-view=true
